---
- name: Vector | Install rpm package
  become: true
  ansible.builtin.yum:
    name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    state: present
  notify: Vector | Restart vector service